name: Flutter Web
on:
  push:
    branches:
      - github-page
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: cd example
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: ls
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: ls lib
      - run: flutter build web --release --base-href "/shuffle-uikit/"
      - run: |
          cd build/web
          git init
          git config --global user.email ${{secrets.kabzki_email}}
          git config --global user.name Kabzki
          git status
          git remote add origin https://${{secrets.kabzki_pat}}@github.com/Kabzki/shuffle-uikit.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update by github actions"
          git push origin gh-pages -f