name: Flutter Web
on:
  push:
    branches:
      - github-page
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup project
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build for web 
        run: |
          cd example
          flutter build web --release --base-href "/shuffle-uikit/"
      - name: Push to gh-pages branch
        run: |
          cd example/build/web
          git init
          git config --global user.email ${{secrets.kabzki_email}}
          git config --global user.name Kabzki
          git status
          git remote add origin https://${{secrets.kabzki_pat}}@github.com/Kabzki/shuffle-uikit.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update by github actions"
          git push origin gh-pages -f